# Section XII: Footwear, Headgear, Umbrellas, etc. (Chapters 64-67)

SECTION_12_NOTES = """
SECTION XII - FOOTWEAR, HEADGEAR, UMBRELLAS, SUN UMBRELLAS, WALKING-STICKS, SEAT-STICKS, WHIPS, RIDING-CROPS AND PARTS THEREOF; PREPARED FEATHERS AND ARTICLES MADE THEREWITH; ARTIFICIAL FLOWERS; ARTICLES OF HUMAN HAIR

(No section-level notes - see individual chapters 64-67)
"""

