# Section XXII: Special Classification Provisions; Temporary Legislation (Chapters 98-99)

SECTION_22_NOTES = """
SECTION XXII - SPECIAL CLASSIFICATION PROVISIONS; TEMPORARY LEGISLATION; TEMPORARY MODIFICATIONS ESTABLISHED PURSUANT TO TRADE LEGISLATION; ADDITIONAL IMPORT RESTRICTIONS ESTABLISHED PURSUANT TO SECTION 22 OF THE AGRICULTURAL ADJUSTMENT ACT, AS AMENDED

(No section-level notes - see Chapters 98 and 99)
"""

